import type { Metadata } from "next";
import { Oswald } from "next/font/google";
import "./globals.css";

export const oswald = Oswald({
  subsets: ["latin"],
  weight: "600",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={oswald.className}>{children}</body>
    </html>
  );
}
